### PR TITLE
copy editing and reorganizing files

### PR DESCRIPTION
**Pull request by chrisdavidmills**
I have copy edited all the files, and also done some reorganization:

* Given the files appropriate extensions
* Changed the folder name so it doesn't have a space in (this can sometimes cause problems)

I think one thing the instruction file is missing is a bit at the start that actually tells you how to set up the code to work, maybe also with an example extension to load locally?

It'll need to be a Chrome extension, and have Chrome instructions, because as you said, it works in Firefox ;-)

### CODE REVIEW

**Comment by An-Error94** [comment]
I'm sorry to reply after a month, but I was very busy.

I think I followed all your advice. In my opinion, this project is now ready for publication by linking to it on the MDN page regarding @document.

**Comment by chrisdavidmills** [comment]
@An-Error94 I've added a small section here:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@document#Workaround_for_non-supporting_browsers

Does this look OK to you?

**Comment by An-Error94** [comment]
Yes, I like it completely. Thank you very much for help.

**Comment by chrisdavidmills** [comment]
@An-Error94 great! You are very welcome.

**Pull request merged**
